name: Tricore Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  build-tricore:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: [
          "tc4dx",
        ]
        cross_compile: [
            "CROSS_COMPILE=tricore-elf-",
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} \
            CONFIG=null ${{ matrix.cross_compile }}
